-- GENERATED FROM backend/scripts/lib/games-status-rules.js
-- DO NOT EDIT THIS FILE MANUALLY.
WITH base_games AS (
  SELECT
    g.id,
    g.title,
    g.summary AS game_summary,
    g.synopsis AS game_synopsis,
    g.lore AS game_lore,
    g.gameplay_description AS game_gameplay_description,
    g.characters AS game_characters,
    g.dev_anecdotes AS game_dev_anecdotes,
    g.cheat_codes AS game_cheat_codes,
    g.versions AS game_versions,
    g.avg_duration_main AS game_avg_duration_main,
    g.avg_duration_complete AS game_avg_duration_complete,
    g.speedrun_wr AS game_speedrun_wr,
    g.manual_url,
    g.cover_url,
    g.youtube_id,
    g.archive_id,
    g.editorial_status AS stored_editorial_status,
    g.media_status AS stored_media_status,
    g.price_status AS stored_price_status
  FROM public.games g
  WHERE g.type = 'game'
),
editorial_rows AS (
  SELECT
    bg.id,
    COALESCE(NULLIF(BTRIM(ge.summary), ''), NULLIF(BTRIM(bg.game_summary), '')) AS summary,
    COALESCE(NULLIF(BTRIM(ge.synopsis), ''), NULLIF(BTRIM(bg.game_synopsis), '')) AS synopsis,
    COALESCE(NULLIF(BTRIM(ge.lore), ''), NULLIF(BTRIM(bg.game_lore), '')) AS lore,
    COALESCE(NULLIF(BTRIM(ge.gameplay_description), ''), NULLIF(BTRIM(bg.game_gameplay_description), '')) AS gameplay_description,
    COALESCE(NULLIF(BTRIM(ge.characters::text), ''), NULLIF(BTRIM(bg.game_characters::text), '')) AS characters,
    COALESCE(NULLIF(BTRIM(ge.dev_anecdotes::text), ''), NULLIF(BTRIM(bg.game_dev_anecdotes::text), '')) AS dev_anecdotes,
    COALESCE(NULLIF(BTRIM(ge.cheat_codes::text), ''), NULLIF(BTRIM(bg.game_cheat_codes::text), '')) AS cheat_codes,
    COALESCE(NULLIF(BTRIM(ge.versions::text), ''), NULLIF(BTRIM(bg.game_versions::text), '')) AS versions,
    COALESCE(ge.avg_duration_main, bg.game_avg_duration_main) AS avg_duration_main,
    COALESCE(ge.avg_duration_complete, bg.game_avg_duration_complete) AS avg_duration_complete,
    COALESCE(NULLIF(BTRIM(ge.speedrun_wr::text), ''), NULLIF(BTRIM(bg.game_speedrun_wr::text), '')) AS speedrun_wr
  FROM base_games bg
  LEFT JOIN public.game_editorial ge ON ge.game_id = bg.id
),
editorial_signals AS (
  SELECT
    er.id AS game_id,
    (CASE WHEN CHAR_LENGTH(BTRIM(COALESCE(er.lore, ''))) >= 1 THEN 1 ELSE 0 END) + (CASE WHEN CHAR_LENGTH(BTRIM(COALESCE(er.gameplay_description, ''))) >= 1 THEN 1 ELSE 0 END) + (CASE WHEN (er.characters IS NOT NULL) AND BTRIM(er.characters::text) <> '' AND BTRIM(er.characters::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) + (CASE WHEN (er.dev_anecdotes IS NOT NULL) AND BTRIM(er.dev_anecdotes::text) <> '' AND BTRIM(er.dev_anecdotes::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) + (CASE WHEN (er.cheat_codes IS NOT NULL) AND BTRIM(er.cheat_codes::text) <> '' AND BTRIM(er.cheat_codes::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) + (CASE WHEN (er.versions IS NOT NULL) AND BTRIM(er.versions::text) <> '' AND BTRIM(er.versions::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) + (CASE WHEN (er.avg_duration_main IS NOT NULL) THEN 1 ELSE 0 END) + (CASE WHEN (er.avg_duration_complete IS NOT NULL) THEN 1 ELSE 0 END) + (CASE WHEN (er.speedrun_wr IS NOT NULL) AND BTRIM(er.speedrun_wr::text) <> '' AND BTRIM(er.speedrun_wr::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) AS additional_signal_count,
    ((CASE WHEN CHAR_LENGTH(BTRIM(COALESCE(er.summary, ''))) >= 1 THEN 1 ELSE 0 END) + (CASE WHEN CHAR_LENGTH(BTRIM(COALESCE(er.synopsis, ''))) >= 1 THEN 1 ELSE 0 END) + (CASE WHEN CHAR_LENGTH(BTRIM(COALESCE(er.lore, ''))) >= 1 THEN 1 ELSE 0 END) + (CASE WHEN CHAR_LENGTH(BTRIM(COALESCE(er.gameplay_description, ''))) >= 1 THEN 1 ELSE 0 END) + (CASE WHEN (er.characters IS NOT NULL) AND BTRIM(er.characters::text) <> '' AND BTRIM(er.characters::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) + (CASE WHEN (er.dev_anecdotes IS NOT NULL) AND BTRIM(er.dev_anecdotes::text) <> '' AND BTRIM(er.dev_anecdotes::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) + (CASE WHEN (er.cheat_codes IS NOT NULL) AND BTRIM(er.cheat_codes::text) <> '' AND BTRIM(er.cheat_codes::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) + (CASE WHEN (er.versions IS NOT NULL) AND BTRIM(er.versions::text) <> '' AND BTRIM(er.versions::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END) + (CASE WHEN (er.avg_duration_main IS NOT NULL) THEN 1 ELSE 0 END) + (CASE WHEN (er.avg_duration_complete IS NOT NULL) THEN 1 ELSE 0 END) + (CASE WHEN (er.speedrun_wr IS NOT NULL) AND BTRIM(er.speedrun_wr::text) <> '' AND BTRIM(er.speedrun_wr::text) NOT IN ('[]', '{}', 'null', '""') THEN 1 ELSE 0 END)) AS total_signal_count,
    (CHAR_LENGTH(BTRIM(COALESCE(er.summary, ''))) >= 70 OR CHAR_LENGTH(BTRIM(COALESCE(er.synopsis, ''))) >= 70) AS primary_is_substantive
  FROM editorial_rows er
),
visible_media AS (
  SELECT
    mr.entity_id AS game_id,
    LOWER(COALESCE(mr.media_type, '')) AS media_type
  FROM public.media_references mr
  WHERE mr.entity_type = 'game'
    AND COALESCE(mr.ui_allowed, true) = true
    AND LOWER(COALESCE(mr.license_status, 'reference_only')) <> 'blocked'
    AND LOWER(COALESCE(mr.healthcheck_status, 'ok')) NOT IN ('broken', 'timeout')
),
media_agg AS (
  SELECT
    bg.id AS game_id,
    COUNT(vm.media_type)::int AS visible_media_count,
    COUNT(DISTINCT CASE WHEN vm.media_type IN ('manual', 'map', 'sprite_sheet', 'ending', 'archive_item', 'youtube_video', 'screenshot', 'scan') THEN vm.media_type END)::int
      + (CASE WHEN (CHAR_LENGTH(BTRIM(COALESCE(bg.manual_url, ''))) >= 1 AND NOT EXISTS (SELECT 1 FROM visible_media vm2 WHERE vm2.game_id = bg.id AND vm2.media_type = 'manual')) THEN 1 ELSE 0 END)
      + (CASE WHEN (CHAR_LENGTH(BTRIM(COALESCE(bg.youtube_id, ''))) >= 1 AND NOT EXISTS (SELECT 1 FROM visible_media vm3 WHERE vm3.game_id = bg.id AND vm3.media_type = 'youtube_video')) THEN 1 ELSE 0 END)
      + (CASE WHEN (CHAR_LENGTH(BTRIM(COALESCE(bg.archive_id, ''))) >= 1 AND NOT EXISTS (SELECT 1 FROM visible_media vm4 WHERE vm4.game_id = bg.id AND vm4.media_type = 'archive_item')) THEN 1 ELSE 0 END)
      AS complete_signal_count,
    CHAR_LENGTH(BTRIM(COALESCE(bg.manual_url, ''))) >= 1 AS has_manual_fallback,
    CHAR_LENGTH(BTRIM(COALESCE(bg.youtube_id, ''))) >= 1 AS has_youtube_fallback,
    CHAR_LENGTH(BTRIM(COALESCE(bg.archive_id, ''))) >= 1 AS has_archive_fallback,
    CHAR_LENGTH(BTRIM(COALESCE(bg.cover_url, ''))) >= 1 AS has_cover_fallback
  FROM base_games bg
  LEFT JOIN visible_media vm ON vm.game_id = bg.id
  GROUP BY bg.id, bg.manual_url, bg.youtube_id, bg.archive_id, bg.cover_url
),
price_agg AS (
  SELECT
    bg.id AS game_id,
    COUNT(ph.game_id)::int AS price_row_count,
    COALESCE(BOOL_OR(COALESCE(LOWER(ph.source), '') NOT IN ('seed', 'seed_local', 'synthetic', 'mock', 'fixture')), false) AS has_real_source
  FROM base_games bg
  LEFT JOIN public.price_history ph ON ph.game_id = bg.id
  GROUP BY bg.id
),
derived AS (
  SELECT
    bg.id,
    bg.title,
    bg.stored_editorial_status,
    bg.stored_media_status,
    bg.stored_price_status,
    CASE
      WHEN es.primary_is_substantive AND es.additional_signal_count >= 2 THEN 'complete'
      WHEN es.total_signal_count > 0 THEN 'partial'
      ELSE 'empty'
    END AS derived_editorial_status,
    CASE
      WHEN ma.complete_signal_count >= 2 THEN 'complete'
      WHEN ma.visible_media_count > 0
        OR ma.has_manual_fallback
        OR ma.has_youtube_fallback
        OR ma.has_archive_fallback
        OR ma.has_cover_fallback
      THEN 'partial'
      ELSE 'empty'
    END AS derived_media_status,
    CASE
      WHEN pa.has_real_source THEN 'real'
      WHEN pa.price_row_count > 0 THEN 'synthetic'
      ELSE 'empty'
    END AS derived_price_status
  FROM base_games bg
  LEFT JOIN editorial_signals es ON es.game_id = bg.id
  LEFT JOIN media_agg ma ON ma.game_id = bg.id
  LEFT JOIN price_agg pa ON pa.game_id = bg.id
)
SELECT jsonb_build_object(
  'rulesVersion', 'phase3-games-status-v1',
  'totalGamesAudited', (SELECT COUNT(*)::int FROM derived),
  'derivedCounts', jsonb_build_object(
    'editorial_status', jsonb_build_object('complete', (SELECT COUNT(*)::int FROM derived WHERE derived_editorial_status = 'complete'), 'partial', (SELECT COUNT(*)::int FROM derived WHERE derived_editorial_status = 'partial'), 'empty', (SELECT COUNT(*)::int FROM derived WHERE derived_editorial_status = 'empty'), 'null', (SELECT COUNT(*)::int FROM derived WHERE derived_editorial_status IS NULL), 'other', (SELECT COUNT(*)::int FROM derived WHERE derived_editorial_status IS NOT NULL AND derived_editorial_status NOT IN ('complete', 'partial', 'empty'))),
    'media_status', jsonb_build_object('complete', (SELECT COUNT(*)::int FROM derived WHERE derived_media_status = 'complete'), 'partial', (SELECT COUNT(*)::int FROM derived WHERE derived_media_status = 'partial'), 'empty', (SELECT COUNT(*)::int FROM derived WHERE derived_media_status = 'empty'), 'null', (SELECT COUNT(*)::int FROM derived WHERE derived_media_status IS NULL), 'other', (SELECT COUNT(*)::int FROM derived WHERE derived_media_status IS NOT NULL AND derived_media_status NOT IN ('complete', 'partial', 'empty'))),
    'price_status', jsonb_build_object('real', (SELECT COUNT(*)::int FROM derived WHERE derived_price_status = 'real'), 'synthetic', (SELECT COUNT(*)::int FROM derived WHERE derived_price_status = 'synthetic'), 'empty', (SELECT COUNT(*)::int FROM derived WHERE derived_price_status = 'empty'), 'null', (SELECT COUNT(*)::int FROM derived WHERE derived_price_status IS NULL), 'other', (SELECT COUNT(*)::int FROM derived WHERE derived_price_status IS NOT NULL AND derived_price_status NOT IN ('real', 'synthetic', 'empty')))
  ),
  'storedCounts', jsonb_build_object(
    'editorial_status', jsonb_build_object('complete', (SELECT COUNT(*)::int FROM derived WHERE stored_editorial_status = 'complete'), 'partial', (SELECT COUNT(*)::int FROM derived WHERE stored_editorial_status = 'partial'), 'empty', (SELECT COUNT(*)::int FROM derived WHERE stored_editorial_status = 'empty'), 'null', (SELECT COUNT(*)::int FROM derived WHERE stored_editorial_status IS NULL), 'other', (SELECT COUNT(*)::int FROM derived WHERE stored_editorial_status IS NOT NULL AND stored_editorial_status NOT IN ('complete', 'partial', 'empty'))),
    'media_status', jsonb_build_object('complete', (SELECT COUNT(*)::int FROM derived WHERE stored_media_status = 'complete'), 'partial', (SELECT COUNT(*)::int FROM derived WHERE stored_media_status = 'partial'), 'empty', (SELECT COUNT(*)::int FROM derived WHERE stored_media_status = 'empty'), 'null', (SELECT COUNT(*)::int FROM derived WHERE stored_media_status IS NULL), 'other', (SELECT COUNT(*)::int FROM derived WHERE stored_media_status IS NOT NULL AND stored_media_status NOT IN ('complete', 'partial', 'empty'))),
    'price_status', jsonb_build_object('real', (SELECT COUNT(*)::int FROM derived WHERE stored_price_status = 'real'), 'synthetic', (SELECT COUNT(*)::int FROM derived WHERE stored_price_status = 'synthetic'), 'empty', (SELECT COUNT(*)::int FROM derived WHERE stored_price_status = 'empty'), 'null', (SELECT COUNT(*)::int FROM derived WHERE stored_price_status IS NULL), 'other', (SELECT COUNT(*)::int FROM derived WHERE stored_price_status IS NOT NULL AND stored_price_status NOT IN ('real', 'synthetic', 'empty')))
  ),
  'divergenceCounts', jsonb_build_object(
    'editorial_status', (SELECT COUNT(*)::int FROM derived WHERE stored_editorial_status IS DISTINCT FROM derived_editorial_status),
    'media_status', (SELECT COUNT(*)::int FROM derived WHERE stored_media_status IS DISTINCT FROM derived_media_status),
    'price_status', (SELECT COUNT(*)::int FROM derived WHERE stored_price_status IS DISTINCT FROM derived_price_status),
    'any_status', (SELECT COUNT(*)::int FROM derived WHERE stored_editorial_status IS DISTINCT FROM derived_editorial_status OR stored_media_status IS DISTINCT FROM derived_media_status OR stored_price_status IS DISTINCT FROM derived_price_status)
  ),
  'missingDerivedCount', (
    SELECT COUNT(*)::int
    FROM derived
    WHERE derived_editorial_status IS NULL
       OR derived_media_status IS NULL
       OR derived_price_status IS NULL
  ),
  'allGamesHaveDerivedStatuses', (
    SELECT COUNT(*) = 0
    FROM derived
    WHERE derived_editorial_status IS NULL
       OR derived_media_status IS NULL
       OR derived_price_status IS NULL
  ),
  'divergenceSamples', COALESCE((
    SELECT jsonb_agg(
      jsonb_build_object(
        'id', sample.id,
        'title', sample.title,
        'stored', jsonb_build_object(
          'editorial_status', sample.stored_editorial_status,
          'media_status', sample.stored_media_status,
          'price_status', sample.stored_price_status
        ),
        'derived', jsonb_build_object(
          'editorial_status', sample.derived_editorial_status,
          'media_status', sample.derived_media_status,
          'price_status', sample.derived_price_status
        )
      )
    )
    FROM (
      SELECT *
      FROM derived
      WHERE stored_editorial_status IS DISTINCT FROM derived_editorial_status
         OR stored_media_status IS DISTINCT FROM derived_media_status
         OR stored_price_status IS DISTINCT FROM derived_price_status
      ORDER BY id ASC
      LIMIT 25
    ) AS sample
  ), '[]'::jsonb)
) AS report;
