export const HARDWARE_PROFILES = {
  'game-boy': {
    id: 'game-boy',
    label: 'Game Boy',
    pixelSize: 4,
    body: { w: 28, h: 40, d: 8 },
    cartSlot: { kind: 'top', x: 8, z: 2, w: 12, d: 4, reveal: 16 },
    mediaType: 'cart-gb',
    family: 'handheld',
    portable: true,
    features: ['screen', 'dpad', 'buttons', 'speaker', 'power-led'],
  },
  snes: {
    id: 'snes',
    label: 'Super Nintendo',
    pixelSize: 5,
    body: { w: 34, h: 8, d: 26 },
    cartSlot: { kind: 'top', x: 11, z: 8, w: 12, d: 7, reveal: 12 },
    mediaType: 'cart-snes',
    family: 'top-loader',
    features: ['power-led', 'buttons', 'front-bay'],
  },
  megadrive: {
    id: 'megadrive',
    label: 'Mega Drive',
    pixelSize: 5,
    body: { w: 34, h: 9, d: 24 },
    cartSlot: { kind: 'top', x: 13, z: 10, w: 10, d: 6, reveal: 14 },
    mediaType: 'cart-md',
    family: 'megadrive',
    features: ['ring', 'power-led', 'front-bay'],
  },
  ps1: {
    id: 'ps1',
    label: 'PlayStation',
    pixelSize: 5,
    body: { w: 34, h: 7, d: 26 },
    discSlot: { x: 17, z: 13, r: 8 },
    mediaType: 'disc-cd',
    family: 'disc-top',
    features: ['lid', 'power-led', 'buttons'],
  },
  n64: {
    id: 'n64',
    label: 'Nintendo 64',
    pixelSize: 5,
    body: { w: 30, h: 12, d: 24 },
    cartSlot: { kind: 'top', x: 10, z: 9, w: 10, d: 6, reveal: 12 },
    mediaType: 'cart-n64',
    family: 'n64',
    features: ['ports', 'power-led'],
  },
  'game-boy-advance': {
    id: 'game-boy-advance',
    label: 'Game Boy Advance',
    pixelSize: 4,
    body: { w: 38, h: 22, d: 7 },
    cartSlot: { kind: 'top', x: 12, z: 1, w: 14, d: 4, reveal: 10 },
    mediaType: 'cart-gba',
    family: 'handheld-wide',
    portable: true,
    features: ['screen', 'dpad', 'buttons', 'speaker', 'power-led'],
  },
  saturn: {
    id: 'saturn',
    label: 'Sega Saturn',
    pixelSize: 5,
    body: { w: 34, h: 8, d: 28 },
    discSlot: { x: 17, z: 13, r: 8 },
    mediaType: 'disc-cd',
    family: 'disc-top',
    features: ['lid', 'front-bay', 'power-led'],
  },
  nes: {
    id: 'nes',
    label: 'Nintendo Entertainment System',
    pixelSize: 5,
    body: { w: 36, h: 10, d: 28 },
    cartSlot: { kind: 'front', x: 11, y: 3, w: 14, h: 6, reveal: 12 },
    mediaType: 'cart-nes',
    family: 'front-loader',
    features: ['front-door', 'power-led'],
  },
};

export const HARDWARE_ALIASES = {
  gb: 'game-boy',
  gameboy: 'game-boy',
  gba: 'game-boy-advance',
  gameboyadvance: 'game-boy-advance',
  genesis: 'megadrive',
  'mega-drive': 'megadrive',
  playstation: 'ps1',
  psx: 'ps1',
  'nintendo-64': 'n64',
};

export function resolveHardwareId(consoleId) {
  const normalized = String(consoleId || '').toLowerCase();
  return HARDWARE_PROFILES[normalized] ? normalized : (HARDWARE_ALIASES[normalized] || normalized);
}
